### ISSUE TITLE
Anexo: Políticas de recursos informáticos

### ISSUE THREAD

**Issue by AlexisAndresHR** [AlexisAndresHR/proyecto_final_3ro#17]
Creación del elemento como parte de la documentación del proyecto.

**Comment by IvanHernandezOsornio** [comment]
Estas políticas aquí descritas han tenido como objetivo definir una estructura normativa que permita a la Comunidad hacer el mejor uso posible de los recursos de la biblioteca, que permita promover los objetivos de la biblioteca en un ambiente seguro y claro.
